const faker = require('faker');
const User = require('../models/User');
const Produce = require('../models/Produce');

const produces = [
    "Amaranth Leaves",
    "Arrowroot",
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Bamboo Shoots",
    "Green Beans",
    "Beets",
    "Belgian Endive",
    "Bitter Melon",
    "Bok Choy",
    "Broadbeans",
    "Broccoli",
    "Broccoli Rabe",
    "Brussel Sprouts",
    "Green Cabbage",
    "Red Cabbage",
    "Carrot",
    "Cassava",
    "Cauliflower",
    "Celeriac",
    "Celery",
    "Chayote",
    "Chicory",
    "Collards",
    "Corn",
    "Crookneck",
    "Cucumber",
    "Daikon",
    "Dandelion Greens",
    "Edamame",
    "Eggplant",
    "Fennel",
    "Fiddleheads",
    "Ginger Root",
    "Horseradish",
    "Jicama",
    "Kale",
    "Kohlrabi",
    "Leeks",
    "Iceberg Lettuce",
    "Lettuce",
    "Romaine Lettuce",
    "Mushrooms",
    "Mustard Greens",
    "Okra",
    "Red Onion",
    "Onions",
    "Parsnip",
    "Green Peas",
    "Green Pepper",
    "Red Pepper",
    "Sweet Red Pepper",
    "Red Potato",
    "White Potato",
    "Yellow Potato",
    "Pumpkin",
    "Radicchio",
    "Radishes",
    "Rutabaga",
    "Salsify",
    "Shallots",
    "Snow Peas",
    "Sorrel",
    "Spaghetti Squash",
    "Spinach",
    "Butternut Squash",
    "Sugar Snap Peas",
    "Sweet Potato",
    "Swiss Chard",
    "Tomatillo",
    "Tomato",
    "Turnip",
    "Watercress",
    "Yam Root",
    "Zucchini",
    "Acerola",
    "Pomme",
    "Apple",
    "Apricots",
    "Avocado",
    "Banana",
    "Blackberries",
    "Blackcurrant",
    "Blueberries",
    "Breadfruit",
    "Cantaloupe",
    "Carambola",
    "Cherimoya",
    "Cherries",
    "Clementine",
    "Coconut Meat",
    "Cranberries",
    "Apple",
    "Date Fruit",
    "Durian",
    "Elderberries",
    "Feijoa",
    "Figs",
    "Gooseberries",
    "Grapefruit",
    "Grapes",
    "Guava",
    "Honeydew Melon",
    "Jackfruit",
    "Java Plum",
    "Jujube Fruit",
    "Kiwifruit",
    "Kumquat",
    "Lemon",
    "lime",
    "Lime",
    "Longan",
    "Loquat",
    "Lychee",
    "Mandarin",
    "Mango",
    "Mangosteen",
    "Mulberries",
    "Nectarine",
    "Olives",
    "Orange",
    "Papaya",
    "Passion Fruit",
    "Peaches",
    "Pear",
    "Persimmon",
    "Pineapple",
    "Pitanga",
    "Plantain",
    "Plums",
    "Pomegranate",
    "Prickly Pear",
    "Prunes",
    "Pummelo",
    "Quince",
    "Raspberries",
    "Rhubarb",
    "Rose",
    "Sapodilla",
    "Sapote",
    "Soursop",
    "Strawberries",
    "Sugar Apple",
    "Tamarind",
    "Tangerine",
    "Watermelon"];

module.exports = seedProduces = async () => {
    const nums = [1,2,3,4,5];
    Produce.deleteMany({}).then((res) => console.log(`Deleted ${res.deletedCount} produces.`));
    return new Promise(async (res, rej) => {
        let baseLat = 37.8715;
        let baseLng = -122.27275;
        for (let index = 0; index < produces.length; index++) {
            let lat = baseLat + (Math.random() - .5);
            let lng = baseLng + Math.random();
           
            var random = Math.floor(Math.random() * 10)
            const randomUser = await User.findOne().skip(random)

            const newProduce = await new Produce({
                        public: faker.random.boolean(),
                        accessible: nums[index % nums.length],
                        ownerPermission: nums[index % nums.length],
                        quality: nums[index % nums.length],
                        abundance: nums[index % nums.length],
                        name: produces[index],
                        user: randomUser._id,
                        type: "Produce",
                        lat: lat,
                        lng: lng
                    });

            await newProduce.save()
                    .then((produce) => console.log(`Success: produce ${index} was created`),
                    (err) => console.log(`Produce_${index} was unable to save due to: ${err}`))
            await randomUser.produces.push(newProduce._id);
            await randomUser.save()
                    .then((user) => console.log(`Success: User ${user.username} was re-saved with more produce`),
                    (err) => console.log(`User_${index} was unable to re-save due to: ${err}`))    
            const numProduce = await Produce.count();
            if (index >= (produces.length - 1) && numProduce >= (produces.length - 1)) {
                return res("All produce successfully created");
            } else if (index >= (produces.length - 1)) {
                return rej(`All produce was not successfully created, only created ${numProduce} produce`);
            }
            }
        }
    )}